apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - deployment.yaml

images:
  - name: k8s-controller
    newName: shamimice03/my-controller
    newTag: v1.0.0

namespace: default
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: k8s-controller
      app.kubernetes.io/part-of: k8s-controller
